name: Outlands
description: $description
version: '${version}'

main: net.omni.outlands.OutlandsPlugin
api-version: '1.21'
load: POSTWORLD

softdepend: [ PlaceholderAPI, ProtocolLib, MythicMobs, MMOItems, ItemEdit, Nexo ]

authors: [ domninos ]

commands:
  outlands:
    description: Enter the Outlands or manage the plugin
    aliases: [ol]
  extract:
    description: Extract from the Outlands early
    aliases: [ext]
  areas:
    description: Manage Outlands areas
    aliases: [area]
    permission: outlands.areas

permissions:
  outlands.*:
    description: Grants all Outlands permissions
    children:
      outlands.admin: true
      outlands.play: true
      outlands.areas: true
      outlands.bypass.cooldown: true
  outlands.admin:
    description: Allows managing the Outlands plugin
    default: op
  outlands.areas:
    description: Allows managing Outlands areas
    default: op
  outlands.play:
    description: Allows entering the Outlands
    default: true
  outlands.bypass.cooldown:
    description: Bypass the run cooldown
    default: false
